### ISSUE TITLE
404 callback page

### ISSUE THREAD

**Issue by doko89** [hotspotbilling/phpnuxbill-xendit#1]
assalamualaikum mas.

untuk halaman callback kenapa response nya Not Found ya,
ini log nginx nya

![image](https://github.com/hotspotbilling/phpnuxbill/assets/20936390/81e8d8a2-67bf-4f4e-9f4e-a69a272941f2)

**Comment by ibnux** [comment]
waalaikum salam,

iya, callback ngga saya pakai, karena kondisi banyak yang install di Local Network, nanti di perbaiki di sisi plugin
